### ISSUE TITLE
Example project does not run

### ISSUE THREAD

**Issue by patik** [Luehang/react-native-gallery-swiper#9]
I'm on a Mac with the latest MacOS, XCode 3.2, and Node 11.4. The iOS simulator is launched shortly before the script fails in the terminal. I tried running the .xcodeproj file in XCode but it has ~50 errors when attempting to build.

I get the following output when I try to run the example project per the readme instructions:

```sh
❯ npm run ios

> react-native-gallery-swiper-example@1.0.0 ios /Users/craigpatik/Projects/react-native-gallery-swiper/example
> react-native run-ios

info Found Xcode project ReactNativeGallerySwiperExample.xcodeproj
info Building using "xcodebuild -project ReactNativeGallerySwiperExample.xcodeproj -configuration Debug -scheme ReactNativeGallerySwiperExample -destination id=9C768E05-14D8-4C75-A117-BE1D48BF0771 -derivedDataPath build/ReactNativeGallerySwiperExample"
▸ Running script 'Start Packager'
▸ Running script 'Include RCTJSCProfiler'
▸ Linking ReactNativeGallerySwiperExample

❌  ld: symbol(s) not found for architecture x86_64



❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)


error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening ReactNativeGallerySwiperExample.xcodeproj

** BUILD FAILED **


The following build commands failed:
	Ld /Users/craigpatik/Projects/react-native-gallery-swiper/example/ios/build/ReactNativeGallerySwiperExample/Build/Products/Debug-iphonesimulator/ReactNativeGallerySwiperExample.app/ReactNativeGallerySwiperExample normal x86_64
(1 failure)
. Run CLI with --verbose flag for more details.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-native-gallery-swiper-example@1.0.0 ios: `react-native run-ios`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-native-gallery-swiper-example@1.0.0 ios script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/craigpatik/.npm/_logs/2019-04-17T08_01_15_413Z-debug.log
```

Here is the NPM debug log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/craigpatik/.nvm/versions/node/v11.8.0/bin/node',
1 verbose cli   '/Users/craigpatik/.nvm/versions/node/v11.8.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'ios' ]
2 info using npm@6.5.0
3 info using node@v11.8.0
4 verbose run-script [ 'preios', 'ios', 'postios' ]
5 info lifecycle react-native-gallery-swiper-example@1.0.0~preios: react-native-gallery-swiper-example@1.0.0
6 info lifecycle react-native-gallery-swiper-example@1.0.0~ios: react-native-gallery-swiper-example@1.0.0
7 verbose lifecycle react-native-gallery-swiper-example@1.0.0~ios: unsafe-perm in lifecycle true
8 verbose lifecycle react-native-gallery-swiper-example@1.0.0~ios: PATH: /Users/craigpatik/.nvm/versions/node/v11.8.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/craigpatik/Projects/react-native-gallery-swiper/example/node_modules/.bin:/usr/local/opt/openssl/bin:/Users/craigpatik/.nvm/versions/node/v11.8.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/craigpatik/Library/Android/sdk/emulator:/Users/craigpatik/Library/Android/sdk/tools:/Users/craigpatik/Library/Android/sdk/tools/bin:/Users/craigpatik/Library/Android/sdk/platform-tools:/usr/local/opt/fzf/bin
9 verbose lifecycle react-native-gallery-swiper-example@1.0.0~ios: CWD: /Users/craigpatik/Projects/react-native-gallery-swiper/example
10 silly lifecycle react-native-gallery-swiper-example@1.0.0~ios: Args: [ '-c', 'react-native run-ios' ]
11 silly lifecycle react-native-gallery-swiper-example@1.0.0~ios: Returned: code: 1  signal: null
12 info lifecycle react-native-gallery-swiper-example@1.0.0~ios: Failed to exec ios script
13 verbose stack Error: react-native-gallery-swiper-example@1.0.0 ios: `react-native run-ios`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/craigpatik/.nvm/versions/node/v11.8.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:197:13)
13 verbose stack     at ChildProcess.<anonymous> (/Users/craigpatik/.nvm/versions/node/v11.8.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:197:13)
13 verbose stack     at maybeClose (internal/child_process.js:978:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
14 verbose pkgid react-native-gallery-swiper-example@1.0.0
15 verbose cwd /Users/craigpatik/Projects/react-native-gallery-swiper/example
16 verbose Darwin 18.2.0
17 verbose argv "/Users/craigpatik/.nvm/versions/node/v11.8.0/bin/node" "/Users/craigpatik/.nvm/versions/node/v11.8.0/bin/npm" "run" "ios"
18 verbose node v11.8.0
19 verbose npm  v6.5.0
20 error code ELIFECYCLE
21 error errno 1
22 error react-native-gallery-swiper-example@1.0.0 ios: `react-native run-ios`
22 error Exit status 1
23 error Failed at the react-native-gallery-swiper-example@1.0.0 ios script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by Luehang** [comment]
Hi patik,

`react-native-gallery-swiper` is constantly being updated and the example project just hasn't been updating with it constantly.  To temporarily fix this problem, paste the following codes to your project. 


## :watch: Performance Optimization List Example

> If you like [`react-native-gallery-swiper`](https://github.com/Luehang/react-native-gallery-swiper), please be sure to give it a star at [GitHub](https://github.com/Luehang/react-native-gallery-swiper). Thanks.

```javascript
import GallerySwiper from "react-native-gallery-swiper";

//...
render() {
    return (
        <GallerySwiper
            images={[
                { uri: "https://luehangs.site/pic-chat-app-images/beautiful-blond-blonde-hair-478544.jpg",
                    // Optional: Adding a dimensions or height and
                    // width field with the actual width and height
                    // for REMOTE IMAGES will help improve performance.
                    dimensions: { width: 1080, height: 1920 } },
                { uri: "https://luehangs.site/pic-chat-app-images/beautiful-beautiful-women-beauty-40901.jpg",
                    dimensions: { width: 1080, height: 1920 } },
                { uri: "https://luehangs.site/pic-chat-app-images/animals-avian-beach-760984.jpg",
                    dimensions: { width: 1080, height: 1920 } },
                { uri: "https://luehangs.site/pic-chat-app-images/beautiful-blond-fishnet-stockings-48134.jpg",
                    dimensions: { width: 1080, height: 1920 } },
                { uri: "https://luehangs.site/pic-chat-app-images/beautiful-beautiful-woman-beauty-9763.jpg",
                    dimensions: { width: 1080, height: 1920 } },
                { uri: "https://luehangs.site/pic-chat-app-images/attractive-balance-beautiful-186263.jpg",
                    dimensions: { width: 1920, height: 1080 } },
                // Test with 10 to over 100s to 1000s of images
                // ...
                // ...
                // ...
            ]}
            // Change this to render how many items before it.
            initialNumToRender={2}
            // Turning this off will make it feel faster
            // and prevent the scroller to slow down
            // on fast swipes.
            sensitiveScroll={false}
        />
    );
}
//...
```

<br/>

The example project will be looked at soon and will be fix and updated.
